### ISSUE TITLE
Modify users playbook to install ohmyzsh

### ISSUE THREAD

**Issue by count-null** [count-null/ansible#10]
Currently when you run users, the first time you log in, zsh menu pops up prompting a config selection. This is zsh default behavior when there is no ~/.zshrc file in the user's home.

We will fix this by installing OhMyZSH https://ohmyz.sh - it's a plugin system for zsh and by installing it, it should also create that ~/.zshrc file.

It should download it to the `/tmp` directory. In Linux, the contents of this directory are automatically deleted on reboot. It's for temp files. 

Using ansible download and run the install.sh script that installs ohmyzsh. 

Test that it works by creating a new user and log in as that user. It should not ask for any input this time.

**Comment by Dylan-Toms** [comment]
Done
